spring:
  application:
    name: microservice-discovery-eureka
  security:
    user:
      name: nsk
      password: abcd1234
server:
  port: 8764
eureka:
  client:
    # 部署Eureka Server集群时，register-with-eureka和fetch-registry应为true
    # 表示是否将自己注册到Eureka Server
    register-with-eureka: false
    # 表示是否从Eureka Server获取注册信息
    fetch-registry: false
    # 设置与Eureka Server交互的地址
    service-url:
       defaultZone: http://nsk:abcd1234@localhost:8764/eureka/

---
#profiles = peer1时配置信息
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://nsk:abcd1234@peer2:8762/eureka/
---
# profiles = peer2时配置信息
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2
  client:
    service-url:
      defaultZone: http://nsk:abcd1234@peer1:8761/eureka/